Rural_House: businessLogic.ApplicationFacadeInterfaceWS Interface Reference
businessLogic.ApplicationFacadeInterfaceWS Interface Reference
Public Member Functions
Offer createOffer (RuralHouse ruralHouse, Date firstDay, Date lastDay, float price) throws OverlappingOfferExists, BadDates
This method creates an offer with a house number, first day, last day and price.
Vector< RuralHouse > getAllRuralHouses ()
This method creates a book with a corresponding parameters.
Vector< Offer > getOffers (RuralHouse rh, Date firstDay, Date lastDay)
This method obtains the offers of a ruralHouse in the provided dates.
void initializeBD ()
void bookOffer (Offer bookOffer)
boolean coincide (RuralHouse houseCode, Date firstDay, Date lastDay)
Detailed Description
Definition at line 16 of file ApplicationFacadeInterfaceWS.java.
Member Function Documentation
bookOffer()
void businessLogic.ApplicationFacadeInterfaceWS.bookOffer (Offer bookOffer)
Implemented in businessLogic.FacadeImplementationWS.
Referenced by bean.Query_Bean.book().
coincide()
boolean businessLogic.ApplicationFacadeInterfaceWS.coincide (RuralHouse houseCode, Date firstDay, Date lastDay)
Implemented in businessLogic.FacadeImplementationWS.
Referenced by bean.Set_Bean.createOffer().
createOffer()
Offer businessLogic.ApplicationFacadeInterfaceWS.createOffer (RuralHouse ruralHouse, Date firstDay, Date lastDay, float price) throws OverlappingOfferExists, BadDates
This method creates an offer with a house number, first day, last day and price.
Parameters
House number, start day, last day and price
Returns
None
Implemented in businessLogic.FacadeImplementationWS.
Referenced by bean.Set_Bean.createOffer().
getAllRuralHouses()
Vector<RuralHouse> businessLogic.ApplicationFacadeInterfaceWS.getAllRuralHouses ()
This method creates a book with a corresponding parameters.
Parameters
First day, last day, house number and telephone
Returns
a bookThis method retrieves the existing rural houses
a Set of rural houses
Implemented in businessLogic.FacadeImplementationWS.
Referenced by bean.Initialize.main(), bean.Query_Bean.Query_Bean(), and bean.Set_Bean.Set_Bean().
getOffers()
Vector<Offer> businessLogic.ApplicationFacadeInterfaceWS.getOffers (RuralHouse rh, Date firstDay, Date lastDay)
This method obtains the offers of a ruralHouse in the provided dates.
Parameters
ruralHouse,the ruralHouse to inspect
firstDay,first day in a period range
lastDay,last day in a period range
Returns
the first offer that overlaps with those dates, or null if there is no overlapping offer
Implemented in businessLogic.FacadeImplementationWS.
Referenced by bean.Query_Bean.searchOffers().
initializeBD()
void businessLogic.ApplicationFacadeInterfaceWS.initializeBD ()
Implemented in businessLogic.FacadeImplementationWS.
Referenced by bean.Initialize.main().
The documentation for this interface was generated from the following file:
src/businessLogic/ApplicationFacadeInterfaceWS.java