.TH "bean.Facade_Bean" 3 "Fri Mar 15 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bean.Facade_Bean
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBApplicationFacadeInterfaceWS\fP \fBgetBusinessLogic\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final \fBApplicationFacadeInterfaceWS\fP \fBfacadeBl\fP = new \fBFacadeImplementationWS\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Facade_Bean\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBApplicationFacadeInterfaceWS\fP bean\&.Facade_Bean\&.getBusinessLogic ()\fC [static]\fP"

.PP
Definition at line 11 of file Facade_Bean\&.java\&.
.PP
.nf
12     {
13         return facadeBl;
14     }
.fi
.PP
References bean\&.Facade_Bean\&.facadeBl\&.
.PP
Referenced by bean\&.Query_Bean\&.Query_Bean(), and bean\&.Set_Bean\&.Set_Bean()\&.
.SH "Member Data Documentation"
.PP 
.SS "final \fBApplicationFacadeInterfaceWS\fP bean\&.Facade_Bean\&.facadeBl = new \fBFacadeImplementationWS\fP()\fC [static]\fP"

.PP
Definition at line 9 of file Facade_Bean\&.java\&.
.PP
Referenced by bean\&.Facade_Bean\&.getBusinessLogic()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
