.TH "bean" 3 "Fri Mar 15 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bean
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFacade_Bean\fP"
.br
.ti -1c
.RI "class \fBInitialize\fP"
.br
.ti -1c
.RI "class \fBQuery_Bean\fP"
.br
.ti -1c
.RI "class \fBSet_Bean\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
