Rural House: modelo.dominio.HibernateUtil Class Reference
modelo.dominio.HibernateUtil Class Reference
Static Public Member Functions
static SessionFactory getSessionFactory ()
Static Private Member Functions
static SessionFactory buildSessionFactory ()
Static Private Attributes
static final SessionFactory sessionFactory = buildSessionFactory()
Detailed Description
Definition at line 6 of file HibernateUtil.java.
Member Function Documentation
buildSessionFactory()
static SessionFactory modelo.dominio.HibernateUtil.buildSessionFactory () static private
Definition at line 9 of file HibernateUtil.java.
     {
         try
         {
             return new Configuration().configure().buildSessionFactory();
             // Crea una instancia de SessionFactory con los datos de configuración
             // de hibernate.cfg.xml, que debe colocarse en el subdirectorio src
             // Si se creara la instancia de SessionFactory de la siguiente manera:
             // new Configuration().configure(new
             // File("hibernate.cfg.xml")).buildSessionFactory();
             // entonces, habría que colocar el fichero en el directorio raíz del proyecto
             // Y no tendría por qué llamarse "hibernate.cfg.xml" sino el nombre que se
             // quiera }
         }
         catch (Throwable ex)
         {
             System.err.println("Fallo creando el SessionFactory." + ex);
             throw new ExceptionInInitializerError(ex);
         }
     }
getSessionFactory()
static SessionFactory modelo.dominio.HibernateUtil.getSessionFactory () static
Definition at line 30 of file HibernateUtil.java.
     {
         return sessionFactory;
     }
References modelo.dominio.HibernateUtil.sessionFactory.
Referenced by dataAccess.HibernateDataAccess.bookOffer(), dataAccess.HibernateDataAccess.coincide(), dataAccess.HibernateDataAccess.createOffer(), dataAccess.HibernateDataAccess.existsOverlappingOffer(), dataAccess.HibernateDataAccess.getAllRuralHouses(), dataAccess.HibernateDataAccess.getOffers(), and businessLogic.FacadeImplementationWS.initializeBD().
Member Data Documentation
sessionFactory
final SessionFactory modelo.dominio.HibernateUtil.sessionFactory = buildSessionFactory() static private
Definition at line 7 of file HibernateUtil.java.
Referenced by modelo.dominio.HibernateUtil.getSessionFactory().
The documentation for this class was generated from the following file:
src/modelo/dominio/HibernateUtil.java