Rural House: bean.Facade_Bean Class Reference
bean.Facade_Bean Class Reference
Static Public Member Functions
static ApplicationFacadeInterfaceWS getBusinessLogic ()
Static Public Attributes
static final ApplicationFacadeInterfaceWS facadeBl = new FacadeImplementationWS()
Detailed Description
Definition at line 6 of file Facade_Bean.java.
Member Function Documentation
getBusinessLogic()
static ApplicationFacadeInterfaceWS bean.Facade_Bean.getBusinessLogic () static
Definition at line 11 of file Facade_Bean.java.
     {
         return facadeBl;
     }
References bean.Facade_Bean.facadeBl.
Referenced by bean.Query_Bean.Query_Bean(), and bean.Set_Bean.Set_Bean().
Member Data Documentation
facadeBl
final ApplicationFacadeInterfaceWS bean.Facade_Bean.facadeBl = new FacadeImplementationWS() static
Definition at line 9 of file Facade_Bean.java.
Referenced by bean.Facade_Bean.getBusinessLogic().
The documentation for this class was generated from the following file:
src/bean/Facade_Bean.java