.TH "bean.Initialize" 3 "Tue Mar 12 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bean.Initialize
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Initialize\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void bean\&.Initialize\&.main (String [] args)\fC [static]\fP"

.PP
Definition at line 12 of file Initialize\&.java\&.
.PP
.nf
13     {
14         ApplicationFacadeInterfaceWS facadeBl = new FacadeImplementationWS();
15         facadeBl\&.initializeBD();
16         Vector<RuralHouse> houses = facadeBl\&.getAllRuralHouses();
17     }
.fi
.PP
References businessLogic\&.ApplicationFacadeInterfaceWS\&.getAllRuralHouses(), and businessLogic\&.ApplicationFacadeInterfaceWS\&.initializeBD()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
