.TH "bean.Set_Bean" 3 "Tue Mar 12 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bean.Set_Bean
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSet_Bean\fP ()"
.br
.ti -1c
.RI "\fBRuralHouse\fP \fBgetHouseCode\fP ()"
.br
.ti -1c
.RI "void \fBsetHouseCode\fP (\fBRuralHouse\fP \fBhouseCode\fP)"
.br
.ti -1c
.RI "int \fBgetPrice\fP ()"
.br
.ti -1c
.RI "void \fBsetPrice\fP (int \fBprice\fP)"
.br
.ti -1c
.RI "Date \fBgetFirstDay\fP ()"
.br
.ti -1c
.RI "void \fBsetFirstDay\fP (Date \fBfirstDay\fP)"
.br
.ti -1c
.RI "Date \fBgetLastDay\fP ()"
.br
.ti -1c
.RI "void \fBsetLastDay\fP (Date \fBlastDay\fP)"
.br
.ti -1c
.RI "List< \fBRuralHouse\fP > \fBgetHouses\fP ()"
.br
.ti -1c
.RI "void \fBsetHouses\fP (List< \fBRuralHouse\fP > \fBhouses\fP)"
.br
.ti -1c
.RI "void \fBonDateSelect\fP (SelectEvent event)"
.br
.ti -1c
.RI "String \fBcreateOffer\fP ()"
.br
.ti -1c
.RI "String \fBgetError\fP ()"
.br
.ti -1c
.RI "void \fBsetError\fP (String \fBerror\fP)"
.br
.ti -1c
.RI "boolean \fBisShowError\fP ()"
.br
.ti -1c
.RI "void \fBsetShowError\fP (boolean \fBshowError\fP)"
.br
.ti -1c
.RI "void \fBerrorFalse\fP ()"
.br
.ti -1c
.RI "void \fBborrar\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBerror\fP"
.br
.ti -1c
.RI "boolean \fBshowError\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRuralHouse\fP \fBhouseCode\fP"
.br
.ti -1c
.RI "int \fBprice\fP"
.br
.ti -1c
.RI "Date \fBfirstDay\fP"
.br
.ti -1c
.RI "Date \fBlastDay\fP"
.br
.ti -1c
.RI "List< \fBRuralHouse\fP > \fBhouses\fP"
.br
.ti -1c
.RI "\fBApplicationFacadeInterfaceWS\fP \fBfacadeBL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Set_Bean\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bean\&.Set_Bean\&.Set_Bean ()"

.PP
Definition at line 31 of file Set_Bean\&.java\&.
.PP
.nf
32     {
33         facadeBL = Facade_Bean\&.getBusinessLogic();
34         houses = facadeBL\&.getAllRuralHouses();
35     }
.fi
.PP
References bean\&.Set_Bean\&.facadeBL, businessLogic\&.ApplicationFacadeInterfaceWS\&.getAllRuralHouses(), bean\&.Facade_Bean\&.getBusinessLogic(), and bean\&.Set_Bean\&.houses\&.
.SH "Member Function Documentation"
.PP 
.SS "void bean\&.Set_Bean\&.borrar ()"

.PP
Definition at line 171 of file Set_Bean\&.java\&.
.PP
.nf
172     {
173         price = 0;
174         firstDay = null;
175         lastDay = null;
176     }
.fi
.PP
References bean\&.Set_Bean\&.firstDay, bean\&.Set_Bean\&.lastDay, and bean\&.Set_Bean\&.price\&.
.PP
Referenced by bean\&.Set_Bean\&.createOffer()\&.
.SS "String bean\&.Set_Bean\&.createOffer ()"

.PP
Definition at line 95 of file Set_Bean\&.java\&.
.PP
.nf
96     {
97         if ((firstDay != null) || (lastDay != null) && (firstDay\&.compareTo(lastDay) < 0) && (price > 0)) 
98         {
99             try 
100             {
101                 if (facadeBL\&.coincide(houseCode, firstDay, lastDay) == false) 
102                 {
103                     facadeBL\&.createOffer(houseCode, firstDay, lastDay, price);
104                     error = "Offer create";
105                     showError = true;
106                     borrar();
107                 } 
108                 else 
109                 {
110                     error = "Overlapping Offer";
111                     showError = true;
112                 }
113             } 
114             catch (OverlappingOfferExists e) 
115             {
116                 error = "Overlapping Offer";
117                 showError = true;
118             } 
119             catch (BadDates e) 
120             {
121                 error = "Bad Dates: firstDay < lastDay";
122                 showError = true;
123             } 
124             catch (Exception e) 
125             {
126                 error = "Error";
127                 showError = true;
128             }
129             return null;
130         } 
131         else if (price <= 0) 
132         {
133             error = "Price > 0";
134             showError = true;
135             return null;
136         } 
137         else 
138         {
139             error = "Dates!=null";
140             showError = true;
141             return null;
142         }
143 
144     }
.fi
.PP
References bean\&.Set_Bean\&.borrar(), businessLogic\&.ApplicationFacadeInterfaceWS\&.coincide(), businessLogic\&.ApplicationFacadeInterfaceWS\&.createOffer(), bean\&.Set_Bean\&.error, bean\&.Set_Bean\&.facadeBL, bean\&.Set_Bean\&.firstDay, bean\&.Set_Bean\&.houseCode, bean\&.Set_Bean\&.lastDay, bean\&.Set_Bean\&.price, and bean\&.Set_Bean\&.showError\&.
.SS "void bean\&.Set_Bean\&.errorFalse ()"

.PP
Definition at line 166 of file Set_Bean\&.java\&.
.PP
.nf
167     {
168         showError = false;
169     }
.fi
.PP
References bean\&.Set_Bean\&.showError\&.
.SS "String bean\&.Set_Bean\&.getError ()"

.PP
Definition at line 146 of file Set_Bean\&.java\&.
.PP
.nf
147     {
148         return error;
149     }
.fi
.PP
References bean\&.Set_Bean\&.error\&.
.SS "Date bean\&.Set_Bean\&.getFirstDay ()"

.PP
Definition at line 57 of file Set_Bean\&.java\&.
.PP
.nf
58     {
59         return firstDay;
60     }
.fi
.PP
References bean\&.Set_Bean\&.firstDay\&.
.SS "\fBRuralHouse\fP bean\&.Set_Bean\&.getHouseCode ()"

.PP
Definition at line 37 of file Set_Bean\&.java\&.
.PP
.nf
38     {
39         return houseCode;
40     }
.fi
.PP
References bean\&.Set_Bean\&.houseCode\&.
.SS "List<\fBRuralHouse\fP> bean\&.Set_Bean\&.getHouses ()"

.PP
Definition at line 77 of file Set_Bean\&.java\&.
.PP
.nf
78     {
79         return houses;
80     }
.fi
.PP
References bean\&.Set_Bean\&.houses\&.
.SS "Date bean\&.Set_Bean\&.getLastDay ()"

.PP
Definition at line 67 of file Set_Bean\&.java\&.
.PP
.nf
68     {
69         return lastDay;
70     }
.fi
.PP
References bean\&.Set_Bean\&.lastDay\&.
.SS "int bean\&.Set_Bean\&.getPrice ()"

.PP
Definition at line 47 of file Set_Bean\&.java\&.
.PP
.nf
48     {
49         return price;
50     }
.fi
.PP
References bean\&.Set_Bean\&.price\&.
.SS "boolean bean\&.Set_Bean\&.isShowError ()"

.PP
Definition at line 156 of file Set_Bean\&.java\&.
.PP
.nf
157     {
158         return showError;
159     }
.fi
.PP
References bean\&.Set_Bean\&.showError\&.
.SS "void bean\&.Set_Bean\&.onDateSelect (SelectEvent event)"

.PP
Definition at line 87 of file Set_Bean\&.java\&.
.PP
.nf
88     {
89         FacesContext facesContext = FacesContext\&.getCurrentInstance();
90         SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
91         facesContext\&.addMessage(null,
92                 new FacesMessage(FacesMessage\&.SEVERITY_INFO, "Date Selected", format\&.format(event\&.getObject())));
93     }
.fi
.SS "void bean\&.Set_Bean\&.setError (String error)"

.PP
Definition at line 151 of file Set_Bean\&.java\&.
.PP
.nf
152     {
153         this\&.error = error;
154     }
.fi
.PP
References bean\&.Set_Bean\&.error\&.
.SS "void bean\&.Set_Bean\&.setFirstDay (Date firstDay)"

.PP
Definition at line 62 of file Set_Bean\&.java\&.
.PP
.nf
63     {
64         this\&.firstDay = firstDay;
65     }
.fi
.PP
References bean\&.Set_Bean\&.firstDay\&.
.SS "void bean\&.Set_Bean\&.setHouseCode (\fBRuralHouse\fP houseCode)"

.PP
Definition at line 42 of file Set_Bean\&.java\&.
.PP
.nf
43     {
44         this\&.houseCode = houseCode;
45     }
.fi
.PP
References bean\&.Set_Bean\&.houseCode\&.
.SS "void bean\&.Set_Bean\&.setHouses (List< \fBRuralHouse\fP > houses)"

.PP
Definition at line 82 of file Set_Bean\&.java\&.
.PP
.nf
83     {
84         this\&.houses = houses;
85     }
.fi
.PP
References bean\&.Set_Bean\&.houses\&.
.SS "void bean\&.Set_Bean\&.setLastDay (Date lastDay)"

.PP
Definition at line 72 of file Set_Bean\&.java\&.
.PP
.nf
73     {
74         this\&.lastDay = lastDay;
75     }
.fi
.PP
References bean\&.Set_Bean\&.lastDay\&.
.SS "void bean\&.Set_Bean\&.setPrice (int price)"

.PP
Definition at line 52 of file Set_Bean\&.java\&.
.PP
.nf
53     {
54         this\&.price = price;
55     }
.fi
.PP
References bean\&.Set_Bean\&.price\&.
.SS "void bean\&.Set_Bean\&.setShowError (boolean showError)"

.PP
Definition at line 161 of file Set_Bean\&.java\&.
.PP
.nf
162     {
163         this\&.showError = showError;
164     }
.fi
.PP
References bean\&.Set_Bean\&.showError\&.
.SH "Member Data Documentation"
.PP 
.SS "String bean\&.Set_Bean\&.error\fC [package]\fP"

.PP
Definition at line 25 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.createOffer(), bean\&.Set_Bean\&.getError(), and bean\&.Set_Bean\&.setError()\&.
.SS "\fBApplicationFacadeInterfaceWS\fP bean\&.Set_Bean\&.facadeBL\fC [private]\fP"

.PP
Definition at line 29 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.createOffer(), and bean\&.Set_Bean\&.Set_Bean()\&.
.SS "Date bean\&.Set_Bean\&.firstDay\fC [private]\fP"

.PP
Definition at line 23 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.borrar(), bean\&.Set_Bean\&.createOffer(), bean\&.Set_Bean\&.getFirstDay(), and bean\&.Set_Bean\&.setFirstDay()\&.
.SS "\fBRuralHouse\fP bean\&.Set_Bean\&.houseCode\fC [private]\fP"

.PP
Definition at line 21 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.createOffer(), bean\&.Set_Bean\&.getHouseCode(), and bean\&.Set_Bean\&.setHouseCode()\&.
.SS "List<\fBRuralHouse\fP> bean\&.Set_Bean\&.houses\fC [private]\fP"

.PP
Definition at line 27 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.getHouses(), bean\&.Set_Bean\&.Set_Bean(), and bean\&.Set_Bean\&.setHouses()\&.
.SS "Date bean\&.Set_Bean\&.lastDay\fC [private]\fP"

.PP
Definition at line 24 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.borrar(), bean\&.Set_Bean\&.createOffer(), bean\&.Set_Bean\&.getLastDay(), and bean\&.Set_Bean\&.setLastDay()\&.
.SS "int bean\&.Set_Bean\&.price\fC [private]\fP"

.PP
Definition at line 22 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.borrar(), bean\&.Set_Bean\&.createOffer(), bean\&.Set_Bean\&.getPrice(), and bean\&.Set_Bean\&.setPrice()\&.
.SS "boolean bean\&.Set_Bean\&.showError\fC [package]\fP"

.PP
Definition at line 26 of file Set_Bean\&.java\&.
.PP
Referenced by bean\&.Set_Bean\&.createOffer(), bean\&.Set_Bean\&.errorFalse(), bean\&.Set_Bean\&.isShowError(), and bean\&.Set_Bean\&.setShowError()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
