.TH "businessLogic.ApplicationFacadeInterfaceWS" 3 "Tue Mar 12 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
businessLogic.ApplicationFacadeInterfaceWS
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbusinessLogic\&.FacadeImplementationWS\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOffer\fP \fBcreateOffer\fP (\fBRuralHouse\fP ruralHouse, Date firstDay, Date lastDay, float price)  throws OverlappingOfferExists, BadDates"
.br
.RI "This method creates an offer with a house number, first day, last day and price\&. "
.ti -1c
.RI "Vector< \fBRuralHouse\fP > \fBgetAllRuralHouses\fP ()"
.br
.RI "This method creates a book with a corresponding parameters\&. "
.ti -1c
.RI "Vector< \fBOffer\fP > \fBgetOffers\fP (\fBRuralHouse\fP rh, Date firstDay, Date lastDay)"
.br
.RI "This method obtains the offers of a ruralHouse in the provided dates\&. "
.ti -1c
.RI "void \fBinitializeBD\fP ()"
.br
.ti -1c
.RI "void \fBbookOffer\fP (\fBOffer\fP bookOffer)"
.br
.ti -1c
.RI "boolean \fBcoincide\fP (\fBRuralHouse\fP houseCode, Date firstDay, Date lastDay)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ApplicationFacadeInterfaceWS\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void businessLogic\&.ApplicationFacadeInterfaceWS\&.bookOffer (\fBOffer\fP bookOffer)"

.PP
Implemented in \fBbusinessLogic\&.FacadeImplementationWS\fP\&.
.PP
Referenced by bean\&.Query_Bean\&.book()\&.
.SS "boolean businessLogic\&.ApplicationFacadeInterfaceWS\&.coincide (\fBRuralHouse\fP houseCode, Date firstDay, Date lastDay)"

.PP
Implemented in \fBbusinessLogic\&.FacadeImplementationWS\fP\&.
.PP
Referenced by bean\&.Set_Bean\&.createOffer()\&.
.SS "\fBOffer\fP businessLogic\&.ApplicationFacadeInterfaceWS\&.createOffer (\fBRuralHouse\fP ruralHouse, Date firstDay, Date lastDay, float price) throws \fBOverlappingOfferExists\fP, \fBBadDates\fP"

.PP
This method creates an offer with a house number, first day, last day and price\&. 
.PP
\fBParameters:\fP
.RS 4
\fIHouse\fP number, start day, last day and price 
.RE
.PP
\fBReturns:\fP
.RS 4
None 
.RE
.PP

.PP
Implemented in \fBbusinessLogic\&.FacadeImplementationWS\fP\&.
.PP
Referenced by bean\&.Set_Bean\&.createOffer()\&.
.SS "Vector<\fBRuralHouse\fP> businessLogic\&.ApplicationFacadeInterfaceWS\&.getAllRuralHouses ()"

.PP
This method creates a book with a corresponding parameters\&. 
.PP
\fBParameters:\fP
.RS 4
\fIFirst\fP day, last day, house number and telephone 
.RE
.PP
\fBReturns:\fP
.RS 4
a bookThis method retrieves the existing rural houses
.PP
a Set of rural houses 
.RE
.PP

.PP
Implemented in \fBbusinessLogic\&.FacadeImplementationWS\fP\&.
.PP
Referenced by bean\&.Initialize\&.main(), bean\&.Query_Bean\&.Query_Bean(), and bean\&.Set_Bean\&.Set_Bean()\&.
.SS "Vector<\fBOffer\fP> businessLogic\&.ApplicationFacadeInterfaceWS\&.getOffers (\fBRuralHouse\fP rh, Date firstDay, Date lastDay)"

.PP
This method obtains the offers of a ruralHouse in the provided dates\&. 
.PP
\fBParameters:\fP
.RS 4
\fIruralHouse,the\fP ruralHouse to inspect 
.br
\fIfirstDay,first\fP day in a period range 
.br
\fIlastDay,last\fP day in a period range 
.RE
.PP
\fBReturns:\fP
.RS 4
the first offer that overlaps with those dates, or null if there is no overlapping offer 
.RE
.PP

.PP
Implemented in \fBbusinessLogic\&.FacadeImplementationWS\fP\&.
.PP
Referenced by bean\&.Query_Bean\&.searchOffers()\&.
.SS "void businessLogic\&.ApplicationFacadeInterfaceWS\&.initializeBD ()"

.PP
Implemented in \fBbusinessLogic\&.FacadeImplementationWS\fP\&.
.PP
Referenced by bean\&.Initialize\&.main()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
