.TH "exceptions" 3 "Tue Mar 12 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBadDates\fP"
.br
.ti -1c
.RI "class \fBDB4oManagerCreationException\fP"
.br
.ti -1c
.RI "class \fBOfferCanNotBeBooked\fP"
.br
.ti -1c
.RI "class \fBOverlappingOfferExists\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
