.TH "src/bean/Set_Bean.java" 3 "Tue Mar 12 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bean/Set_Bean.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbean\&.Set_Bean\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbean\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
