.TH "src/businessLogic/ApplicationFacadeInterfaceWS.java" 3 "Fri Mar 15 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/businessLogic/ApplicationFacadeInterfaceWS.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBbusinessLogic\&.ApplicationFacadeInterfaceWS\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbusinessLogic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
