.TH "exceptions.BadDates" 3 "Fri Mar 15 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions.BadDates
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadDates\fP ()"
.br
.ti -1c
.RI "\fBBadDates\fP (String s)"
.br
.RI "This exception is triggered if first date is greater than last date in offers\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file BadDates\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "exceptions\&.BadDates\&.BadDates ()"

.PP
Definition at line 6 of file BadDates\&.java\&.
.PP
.nf
7     {
8         super();
9     }
.fi
.SS "exceptions\&.BadDates\&.BadDates (String s)"

.PP
This exception is triggered if first date is greater than last date in offers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIString\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
None 
.RE
.PP

.PP
Definition at line 17 of file BadDates\&.java\&.
.PP
.nf
18     {
19         super(s);
20     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final long exceptions\&.BadDates\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 4 of file BadDates\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
