.TH "exceptions.DB4oManagerCreationException" 3 "Fri Mar 15 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions.DB4oManagerCreationException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDB4oManagerCreationException\fP ()"
.br
.ti -1c
.RI "\fBDB4oManagerCreationException\fP (String s)"
.br
.RI "This exception is triggered if there is a problem when constructor of DB4oManager is executed\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file DB4oManagerCreationException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "exceptions\&.DB4oManagerCreationException\&.DB4oManagerCreationException ()"

.PP
Definition at line 6 of file DB4oManagerCreationException\&.java\&.
.PP
.nf
7     {
8         super();
9     }
.fi
.SS "exceptions\&.DB4oManagerCreationException\&.DB4oManagerCreationException (String s)"

.PP
This exception is triggered if there is a problem when constructor of DB4oManager is executed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIString\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
None 
.RE
.PP

.PP
Definition at line 18 of file DB4oManagerCreationException\&.java\&.
.PP
.nf
19     {
20         super(s);
21     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final long exceptions\&.DB4oManagerCreationException\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 4 of file DB4oManagerCreationException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
