.TH "exceptions.OfferCanNotBeBooked" 3 "Fri Mar 15 2019" "Version 1" "Rural_House" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions.OfferCanNotBeBooked
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOfferCanNotBeBooked\fP ()"
.br
.ti -1c
.RI "\fBOfferCanNotBeBooked\fP (String s)"
.br
.RI "This exception is triggered if an offer can not be booked\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file OfferCanNotBeBooked\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "exceptions\&.OfferCanNotBeBooked\&.OfferCanNotBeBooked ()"

.PP
Definition at line 6 of file OfferCanNotBeBooked\&.java\&.
.PP
.nf
7     {
8         super();
9     }
.fi
.SS "exceptions\&.OfferCanNotBeBooked\&.OfferCanNotBeBooked (String s)"

.PP
This exception is triggered if an offer can not be booked\&. 
.PP
\fBParameters:\fP
.RS 4
\fIString\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
None 
.RE
.PP

.PP
Definition at line 17 of file OfferCanNotBeBooked\&.java\&.
.PP
.nf
18     {
19         super(s);
20     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final long exceptions\&.OfferCanNotBeBooked\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 4 of file OfferCanNotBeBooked\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rural_House from the source code\&.
